TEMPLATE	= app
LANGUAGE	= C++

CONFIG	+= moc

INCLUDEPATH	+= .

SOURCES	+= main.cpp

FORMS	= spg.ui

######################################################################
# Automatically generated by qmake (1.07a) Fri Sep 5 01:33:50 2008
######################################################################


# Input
